### ISSUE TITLE
Plugin not work when server throw back error response

### ISSUE THREAD

**Issue by huynhthanhbinh** [Kong/kong-plugin-grpc-web#5] opened 2020-06-05 16:43 UTC
Hi, we are currently testing 2 grpc-web support tool for our project, 
1st is this plugin with Kong gateway.
2nd is Envoy Proxy with Kong gateway.

All runs well if no exception is thrown from gRPC Server.
As gRPC return back error response, this plugin did not return back any response to the web client, Envoy Proxy did return the error response !

Could you please check that case ? 
We are looking forward to hearing from you !

**Comment by hutchic** [comment] 2020-06-10 17:02
duplicate of https://github.com/Kong/kong/issues/5988

**Closed as completed by hutchic** 2020-06-10 17:02 UTC
